// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// DeleteResultHelper is an autogenerated mock type for the DeleteResultHelper type
type DeleteResultHelper struct {
	mock.Mock
}
