// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InsertOneResultHelper is an autogenerated mock type for the InsertOneResultHelper type
type InsertOneResultHelper struct {
	mock.Mock
}
